### ISSUE TITLE
Custom action on toolbar icon

### ISSUE THREAD

**Issue by pjominet** [Teradata/covalent-text-editor-nightly#15]
I open my markdown guide via modal and thus I need a custom action on the guide button. 
Looks like this:
```
options: any = {
toolbar: ['bold', 'italic', 'heading', '|', 'link', 'table', '|', 'preview', {
            name: 'guide',
            action: this.openMarkdownGuide(),
            className: 'fa fa-question-circle',
            title: 'Markdown Guide'
        }]
}
```
But the action is undefined. My guess, it does not understand typscript syntax from angular and all examples I found had an additional param 'editor' passed to the function for action.
Maybe this isn't an issue and I missed the solution, but if it is, could you implement this functionality?

(used this as help: https://github.com/sparksuite/simplemde-markdown-editor/issues/183)

**Comment by jcuenod** [comment]
At first glance I see that `this.openMarkdownGuide()` actually calls the function which is not what I assume you are trying to do. Maybe try `this.openMarkdownGuide` without the brackets. This will set the `toolbar.action` property to the `openMarkdownGuide` function rather than its return value.

[Edit:] I should say, I just stumbled on this issue randomly and haven't ever even used this editor so I may be talking complete nonsense but I have strong suspicions :)

**Comment by pjominet** [comment]
Thx @jcuenod,  that did it, somehow at least :) Now I have to figure out why my modal service that is called in that function is undefined. But at least the button on the toolbar seems to work now :D
